# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OrthogonalMeasure
                                 A QGIS plugin
 Orthogonal Measure
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-03
        copyright            : (C) 2026 by Darko Nedic
        email                : office@geo-biz.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):  # noqa: N802 – required by QGIS plugin API
    """Load the OrthogonalMeasure class.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .orthogonal_measure import OrthogonalMeasure

    return OrthogonalMeasure(iface)
