# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OrthogonalMeasure
                                 A QGIS plugin
 Orthogonal Measure – define a local coordinate system on the map
 (origin + Y-axis), then construct points by entering X/Y offsets.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-03
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Darko Nedic
        email                : office@geo-biz.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os.path
from typing import List, Optional, Tuple

from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator, QVariant, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import (
    QgsFeature,
    QgsField,
    QgsGeometry,
    QgsPointXY,
    QgsProject,
    QgsVectorLayer,
)

from .resources import *  # noqa: F401, F403 – registers Qt resources
from .orthogonal_measure_dialog import OrthogonalMeasureDialog
from .ortho_map_tool import OrthogonalMapTool

PLUGIN_NAME = "Orthogonal Measure"

# Type alias for stored constructed points
ConstructedPoint = Tuple[float, float, QgsPointXY]


class OrthogonalMeasure:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """
        :param iface: QGIS interface instance for runtime manipulation.
        :type iface: QgsInterface
        """
        self.iface = iface
        self.canvas = iface.mapCanvas()
        self.plugin_dir = os.path.dirname(__file__)

        # Locale / translation
        locale = QSettings().value("locale/userLocale", "en")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", f"orthogonal_measure_{locale}.qm"
        )
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Instance attributes
        self.actions: List[QAction] = []
        self.menu = self.tr(f"&{PLUGIN_NAME}")

        # Plugin state
        self.map_tool: Optional[OrthogonalMapTool] = None
        self.dlg: Optional[OrthogonalMeasureDialog] = None
        self.previous_tool = None
        self._constructed_points: List[ConstructedPoint] = []

        self.first_start: Optional[bool] = None

    # ---- Translation -------------------------------------------------------

    @staticmethod
    def tr(message: str) -> str:
        """Return the translated string via Qt translation API."""
        return QCoreApplication.translate("OrthogonalMeasure", message)

    # ---- GUI setup / teardown ----------------------------------------------

    def add_action(
        self,
        icon_path: str,
        text: str,
        callback,
        enabled_flag: bool = True,
        add_to_menu: bool = True,
        add_to_toolbar: bool = True,
        status_tip: Optional[str] = None,
        whats_this: Optional[str] = None,
        parent=None,
    ) -> QAction:
        """Add a toolbar icon to the QGIS GUI."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip:
            action.setStatusTip(status_tip)
        if whats_this:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create menu entries and toolbar icons."""
        icon_path = os.path.join(self.plugin_dir, "icon.svg")
        if not os.path.exists(icon_path):
            icon_path = os.path.join(self.plugin_dir, "icon.png")

        self.add_action(
            icon_path,
            text=self.tr(PLUGIN_NAME),
            callback=self.run,
            status_tip=self.tr("Define local axes and construct points"),
            parent=self.iface.mainWindow(),
        )
        self.first_start = True

    def unload(self):
        """Remove the plugin menu item and icon from the QGIS GUI."""
        if self.map_tool:
            self.map_tool.reset()
            self.map_tool = None

        if self.dlg:
            self.iface.removeDockWidget(self.dlg)
            self.dlg.close()
            self.dlg = None

        for action in self.actions:
            self.iface.removePluginMenu(self.tr(f"&{PLUGIN_NAME}"), action)
            self.iface.removeToolBarIcon(action)

    # ---- Core workflow -----------------------------------------------------

    def run(self):
        """Activate the orthogonal-measure map tool."""
        if self.first_start:
            self.first_start = False
            self._init_components()

        self.previous_tool = self.canvas.mapTool()
        self._reset_state()

        self.canvas.setMapTool(self.map_tool)
        self.iface.messageBar().pushInfo(
            PLUGIN_NAME,
            self.tr("Click on the map to set the origin point (Point 1)."),
        )

        self.dlg.setVisible(True)
        self.dlg.raise_()

    def _init_components(self):
        """Create dock panel and map tool and wire up signals (once)."""
        self.dlg = OrthogonalMeasureDialog(self.iface.mainWindow())
        self.map_tool = OrthogonalMapTool(self.canvas)

        # Map-tool signals
        self.map_tool.points_captured.connect(self._on_points_captured)
        self.map_tool.tool_reset.connect(self._on_tool_reset)

        # Panel signals
        self.dlg.construct_requested.connect(self._on_construct)
        self.dlg.reset_requested.connect(self._on_reset)
        self.dlg.export_requested.connect(self._on_export)
        self.dlg.panel_closed.connect(self._on_dialog_closed)

        # Add to QGIS as a dock widget (right side by default)
        self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dlg)

    def _reset_state(self):
        """Reset tool, dialog and stored points for a fresh run."""
        self.map_tool.reset()
        self.dlg.full_reset()
        self._constructed_points.clear()

    # ---- Signal handlers ---------------------------------------------------

    def _on_points_captured(self, origin: QgsPointXY, y_axis_point: QgsPointXY):
        """Both reference points have been placed on the map."""
        self.dlg.set_origin_coord(f"{origin.x():.3f}, {origin.y():.3f}")
        self.dlg.set_yaxis_coord(
            f"{y_axis_point.x():.3f}, {y_axis_point.y():.3f}"
        )
        self.dlg.set_status(
            "Axes defined!  Enter X and Y offsets below and click "
            "'Construct Point'."
        )
        self.dlg.enable_input(True)

        self.iface.messageBar().pushInfo(
            PLUGIN_NAME,
            self.tr("Axes defined. Enter X / Y offset and click Construct."),
        )

    def _on_construct(self, x_val: float, y_val: float):
        """Compute a map point from offsets and visualise it."""
        if self.map_tool.origin is None or self.map_tool.y_axis_point is None:
            return

        result_pt = self.map_tool.compute_point(x_val, y_val)
        self.map_tool.add_result_marker(result_pt, x_val, y_val)
        self._constructed_points.append((x_val, y_val, result_pt))
        self.dlg.add_result_row(x_val, y_val, result_pt.x(), result_pt.y())

        self.iface.messageBar().pushInfo(
            PLUGIN_NAME,
            self.tr(
                f"Point constructed at E {result_pt.x():.3f}, "
                f"N {result_pt.y():.3f}"
            ),
        )

    def _on_reset(self):
        """Reset everything – map tool, dialog, stored points."""
        self._reset_state()
        self.canvas.setMapTool(self.map_tool)

    def _on_tool_reset(self):
        """The map tool reset itself (e.g. via Escape)."""
        self.dlg.full_reset()
        self._constructed_points.clear()

    def _on_dialog_closed(self):
        """Dialog closed – fully deactivate the tool."""
        if self.map_tool:
            self.map_tool.reset()
        if self.previous_tool and self.previous_tool != self.map_tool:
            self.canvas.setMapTool(self.previous_tool)
        else:
            self.canvas.unsetMapTool(self.map_tool)
        self._constructed_points.clear()

    # ---- Export ------------------------------------------------------------

    def _on_export(self):
        """Export constructed points to a temporary memory layer."""
        if not self._constructed_points:
            QMessageBox.information(
                self.dlg, "Export", self.tr("No points to export.")
            )
            return

        layer = self._create_export_layer()
        QgsProject.instance().addMapLayer(layer)

        count = len(self._constructed_points)
        self.iface.messageBar().pushSuccess(
            PLUGIN_NAME,
            self.tr(
                f"Exported {count} point(s) to layer "
                f"'{PLUGIN_NAME} Points'."
            ),
        )

    def _create_export_layer(self) -> QgsVectorLayer:
        """Build a memory layer containing all constructed points."""
        crs = QgsProject.instance().crs()
        layer = QgsVectorLayer(
            f"Point?crs={crs.authid()}",
            f"{PLUGIN_NAME} Points",
            "memory",
        )

        provider = layer.dataProvider()
        provider.addAttributes([
            QgsField("id", QVariant.Int),
            QgsField("x_offset", QVariant.Double),
            QgsField("y_offset", QVariant.Double),
            QgsField("map_e", QVariant.Double),
            QgsField("map_n", QVariant.Double),
        ])
        layer.updateFields()

        features = []
        for idx, (xv, yv, pt) in enumerate(self._constructed_points, start=1):
            feat = QgsFeature(layer.fields())
            feat.setGeometry(QgsGeometry.fromPointXY(pt))
            feat.setAttributes([idx, xv, yv, pt.x(), pt.y()])
            features.append(feat)

        provider.addFeatures(features)
        layer.updateExtents()
        return layer
