# -*- coding: utf-8 -*-
"""
/***************************************************************************
 orthogonal_measureDialog
                                 A QGIS plugin
 orthogonal_measure
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-03
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Darko Nedic
        email                : office@geo-biz.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import Qt, pyqtSignal
from qgis.PyQt.QtWidgets import QTableWidgetItem

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "orthogonal_measure_dialog_base.ui")
)


class _PanelContent(QtWidgets.QWidget, FORM_CLASS):
    """Internal widget that holds all UI elements loaded from the .ui file."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)


class OrthogonalMeasureDialog(QtWidgets.QDockWidget):
    """Dockable panel for the Orthogonal Measure plugin.

    Can be docked into any QGIS dock area (left, right, top, bottom)
    or left floating as an independent window.

    Signals
    -------
    construct_requested(float, float)
        Emitted when the user clicks *Construct Point*.
    reset_requested()
        Emitted when the user clicks *Reset*.
    export_requested()
        Emitted when the user clicks *Export to Layer*.
    panel_closed()
        Emitted when the dock widget is closed.
    """

    construct_requested = pyqtSignal(float, float)
    reset_requested = pyqtSignal()
    export_requested = pyqtSignal()
    panel_closed = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__("Orthogonal Measure", parent)

        # Allow docking everywhere + floating
        self.setAllowedAreas(
            Qt.LeftDockWidgetArea
            | Qt.RightDockWidgetArea
            | Qt.TopDockWidgetArea
            | Qt.BottomDockWidgetArea
        )
        self.setFeatures(
            QtWidgets.QDockWidget.DockWidgetClosable
            | QtWidgets.QDockWidget.DockWidgetMovable
            | QtWidgets.QDockWidget.DockWidgetFloatable
        )

        # Load UI content
        self._ui = _PanelContent(self)
        self.setWidget(self._ui)

        # Convenience references
        self.spinX = self._ui.spinX
        self.spinY = self._ui.spinY
        self.tableResults = self._ui.tableResults
        self.btnExportLayer = self._ui.btnExportLayer

        # Button connections
        self._ui.btnConstruct.clicked.connect(self._on_construct)
        self._ui.btnReset.clicked.connect(self._on_reset)
        self._ui.btnExportLayer.clicked.connect(self._on_export)

        # Enter key in spinboxes triggers Construct
        self.spinX.installEventFilter(self)
        self.spinY.installEventFilter(self)

        self._point_count: int = 0

    # ---- QDockWidget override ----------------------------------------------

    def closeEvent(self, event):
        """Emit panel_closed so the plugin can deactivate the map tool."""
        self.panel_closed.emit()
        super().closeEvent(event)

    # ---- Event filter ------------------------------------------------------

    def eventFilter(self, obj, event) -> bool:
        if (
            obj in (self.spinX, self.spinY)
            and event.type() == event.KeyPress
            and event.key() in (Qt.Key_Return, Qt.Key_Enter)
        ):
            self._on_construct()
            return True
        return super().eventFilter(obj, event)

    # ---- Private slots -----------------------------------------------------

    def _on_construct(self):
        self.construct_requested.emit(self.spinX.value(), self.spinY.value())

    def _on_reset(self):
        self.reset_requested.emit()

    def _on_export(self):
        self.export_requested.emit()

    # ---- Public interface --------------------------------------------------

    def set_status(self, text: str):
        """Update the status label."""
        self._ui.lblStatus.setText(text)

    def set_origin_coord(self, text: str):
        self._ui.lblOriginCoord.setText(text)

    def set_yaxis_coord(self, text: str):
        self._ui.lblYAxisCoord.setText(text)

    def enable_input(self, enabled: bool = True):
        """Enable or disable the coordinate-input group."""
        self._ui.groupInput.setEnabled(enabled)
        if enabled:
            self.spinX.setFocus()
            self.spinX.selectAll()

    def add_result_row(
        self, x_val: float, y_val: float, map_e: float, map_n: float
    ):
        """Append a row to the results table."""
        self._point_count += 1
        row = self.tableResults.rowCount()
        self.tableResults.insertRow(row)
        self.tableResults.setItem(row, 0, QTableWidgetItem(str(self._point_count)))
        self.tableResults.setItem(row, 1, QTableWidgetItem(f"{x_val:.3f}"))
        self.tableResults.setItem(row, 2, QTableWidgetItem(f"{y_val:.3f}"))
        self.tableResults.setItem(
            row, 3, QTableWidgetItem(f"{map_e:.3f}, {map_n:.3f}")
        )
        self.tableResults.scrollToBottom()
        self.btnExportLayer.setEnabled(True)

    def clear_results(self):
        """Clear the results table."""
        self.tableResults.setRowCount(0)
        self._point_count = 0
        self.btnExportLayer.setEnabled(False)

    def full_reset(self):
        """Reset all UI elements to the initial state."""
        self.set_status("Click on the map to set the origin point.")
        self.set_origin_coord("—")
        self.set_yaxis_coord("—")
        self.enable_input(False)
        self.clear_results()
        self.spinX.setValue(0.0)
        self.spinY.setValue(0.0)
